### ISSUE TITLE
Switch Box<Option<T>> with Option<Box<T>>

### ISSUE THREAD

**Issue by erichCompSci** [arlyon/async-stripe#124]
On the original update, when I fixed the infinite recursive type sizes, I made the optionals Box<Option<T>> types instead of Option<Box<T>> types.  The second one is more useful in  making the code easy to write and more intuitive in the Rust programming space apparently.  I'll fix it and make a pull request.

**Comment by arlyon** [comment]
I think after some mulling about with the API, it is better to add special cases to the truly recursive data structures rather than make everything boxed. There is a lot of noise with the change and in the vast majority of cases it is unneeded. I have been experimenting with the API over the holidays and will push a PR when I get back home (and to my yuibkey). More to come soon.

**Comment by erichCompSci** [comment]
There aren't a lot of people using this right now.  I strongly encourage you to remove as much handcoding as you possibly can.  It's really clear from the few months I've been playing with the Stripe OpenAPI that the group doesn't always adhere to set standards.  And manually changed API's will have to be maintained.  I strongly encourage you to move away from manual data structures as much as possible if not everywhere.  That being said, I've said my piece and this is your repo.

**Comment by arlyon** [comment]
Yes, it hinges on the ability to detect these cycles and box appropriately. My approach will hopefully generalise nicely but we'll see. I am going to repoen this until the other PR is ready, as it really depends on whether it can function reliably.

**Comment by arlyon** [comment]
Closing as the PR is merged.
