### ISSUE TITLE
Support Test Clocks

### ISSUE THREAD

**Issue by imalsogreg** [arlyon/async-stripe#141]
Stripe supports this wonderful new thing called a [Test Clock](https://stripe.com/docs/billing/testing/test_clocks), for placing specific customers into timespaces (my twist on "namespaces"), which can be moved forward by API calls, in order to make Stripe generate webhook requests for things like billing cycle transitions, in simulated time. Test Clocks are currently a beta feature and aren't generally available yet.

I'd like to support this in `async-stripe`. A couple of questions:
 - The API  for test clocks isn't present in stripe's openapi spec. Do we need to wait until that changes, or could we add it now behind a cargo flag?
 - It seems that the natural place to configure a Test Clock is in the `CreateCustomer` struct: adding a field `test_clock: Optional<TestClockId>`. However `CreateCustomer` is generated from the openapi spec. I did not see a way in our openapi crate to manually add fields to a particular codegen'd struct. Is there a way?

**Comment by erichCompSci** [comment]
Yes, there is a way.  Here's what you should do.  Create a trait in a user generated file.  You can find these with the _ext extension on their file names.  You then implement the trait for the CreateCustomer struct.  I did this with the LoginLink feature, so that's how I would support the experimental API.  

I think you should add an experimental flag so it doesn't get built by default, but arlyon will get final say on that.

In the future, I would like to support these off brand API's by changing the way in which we generate the Rest code, but that is as significant rewrite of the generation code an not something I can currently support.  Once we do that, we should have access to more Rest API's that work than what we have now.  (This is just me ranting, not important for what you want to do).

**Comment by imalsogreg** [comment]
Thanks for the suggestion. So you're thinking that the trait will provide a new method `.create_with_test_clock(client: Client, params: &CreateCustomer, test_clock: TestClockId)`, rather than patch the `CreateCustomer` type, IIUC?

**Comment by erichCompSci** [comment]
Well, this is what I would consider a patch.  You create the trait and then because you created the trait, you can implement the trait for any type, like CreateCustomer.  But I just looked at the Beta API on the website and this strategy probably won't work here.

The reason is that this is an unnamed parameter inside of the CreateCustomer api hook.  That means that you need to have that field in the struct for the crate to correctly serialize it to json.  The way to hack this (and you should do it in a feature branch and not put this in mainline, in my humble opinion, if you want this functionality now), is to go into the code generation src/main.rs and add an if statement in gen_struct that looks for the Rust Type CreateCustomer or the openapi type create_customer and add the test_clock parameter manually with a type of TestClockId.  This should go after the for loop.

Then you need to create a TestClock struct that looks like the generated structs at the extension level, give it an Id and a frozen field, with appropriate types for both.  Then set up a TestClockId in the ids.rs file.  

I'll say again, don't pull this because it's Beta version so when it's legit it will come out in the OpenAPI and all of this will happen a little more naturally, but if you want to get this to work now, you would have to do something like this.

Sorry for the previous guidance, I didn't realize that CreateCustomer had a hidden field that we don't support so a trait wouldn't work obviously.

**Comment by erichCompSci** [comment]
Sorry, CreateCustomer would not be in gen_struct.  You would need to look for it in gen_generated_schemas, or gen_inferred_params.

One of those two.

**Comment by imalsogreg** [comment]
It works! Tried with an extra method implemented on `Customer`: https://github.com/arlyon/async-stripe/pull/146

A local tests works as expected - customers can be created with a test clock, deleting the clock deletes the customer. The clock can be advanced.

**Comment by imalsogreg** [comment]
Closing this, since there is no work to do, just wait for stripe openapi spec to be updated upstream.
