### ISSUE TITLE
Only box types that we generate ourselves

### ISSUE THREAD

**Issue by arlyon** [arlyon/async-stripe#149]
Right now we box everything, but we'd be able to improve the API enumerating all the types, then, during codegen, only Box the generated types (those with potential cycles).

**Comment by erichCompSci** [comment]
I'm not against this, per say, but I think exceptions should be rare because they make the code more brittle.  When you introduce a class of exceptions, there is always the risk that the stripe teams continues to add them, going forward....  However, if we make it so that fixing the problem is a simple as adding a particular type name to a list, I'm all for this.  It'll be annoying but easy to fix when things break (and because it's Rust, they'll break at compile time.)

**Comment by arlyon** [comment]
This is closed in #160
