### ISSUE TITLE
Use 2021 edition to allow multiple runtimes

### ISSUE THREAD

**Issue by cortopy** [arlyon/async-stripe#220]
I need to use async-stripe in a crate with both blocking and async, but currently 2018 edition uses resolver version 1, which doesn't allow this.

I'm not sure if it would just be a matter of changing the edition, but having the 2021 would allow this.

**Comment by arlyon** [comment]
Hi, we currently have an MSRV of 1.54.0 so changing edition would require bumping that. I will leave this issue open for now. If you'd like to open a PR feel free but we should probably hold off on bumping MSRV too frequently.

Thanks!

**Comment by mzeitlin11** [comment]
@arlyon what do you think about bumping MSRV now? Happy to put up a PR if you support it. CI just broke due to https://github.com/matklad/once_cell/issues/201 (some interesting MSRV discussion there as well). 

Some crates probably used alongside this one: `actix-web` also just bumped MSRV to 1.59 (says because of transitive `time` dep (also 1.59)), and `axum` is at 1.60. This would also allow removing the transitive dep pins:
```
indexmap = {version = "1.0,<1.9.0", optional = true}
time = {version = "0.3,<0.3.10", optional = true}
security-framework = {version = "~2.6.0", optional = true}
bumpalo = {version = "~3.10.0", optional = true}
```

**Comment by arlyon** [comment]
I am open to this, and actually we may have to bump further depending on how my GAT experiments go, but that will be down the line a little when it matures a little.
