### ISSUE TITLE
Amount for inputs should be represented as u64

### ISSUE THREAD

**Issue by tnkemdilim** [arlyon/async-stripe#370]
### Describe the bug

Amount in inputs are currently represented as `i64` in this crate, but based on the Stripe docs, amounts are always positive (for the ones I've noticed so far: [payment intents](https://stripe.com/docs/api/payment_intents/object#payment_intent_object-amount) and [refunds](https://stripe.com/docs/api/refunds/create#create_refund-amount)).

### To Reproduce

See the stripe docs for [payment intents](https://stripe.com/docs/api/payment_intents/object#payment_intent_object-amount) and [refunds](https://stripe.com/docs/api/refunds/create#create_refund-amount).

### Expected behavior

Amounts should be represented as strictly `u64` for payment intent & refund inputs (there might be other places were this also applies, but these are the two(2) I've noticed).

### OS

macos

### Rust version

1.69

### Library version

async-stripe 0.21.0

### API version

2022-11-15

**Comment by arlyon** [comment]
Thanks for opening an issue (and sorry for the reply, I am only now clearing some of the backlog here).

This is a limitation of how stripe choose to expose their API, which is done using OpenAPI, and has no concept of strictly positive numbers or even of sized numbers, only 'integers'.

I am open to doing some metadata override here but we would have to maintain that ourselves since I don't believe it is possible to encode that restraint in the spec.

**Comment by WesleyAC** [comment]
Upstream issue, for reference: https://github.com/stripe/openapi/issues/36
