### ISSUE TITLE
Builder patterns

### ISSUE THREAD

**Issue by antonio-hickey** [arlyon/async-stripe#591]
### Is your feature request related to a problem? Please describe.

I don't like writing code like this
```rs
let mut create_billing_portal = CreateBillingPortalSession::new(users_stripe_cust_id);
create_billing_portal.return_url = Some("https://someurl.com"); 
 
let billing_portal =
        BillingPortalSession::create(&stripe_client, create_billing_portal).await?;
```

### Describe the solution you'd like

I would love to use a builder pattern like so:
```rs
let billing_portal = BillingPortalSession::create(
    &stripe_client, 
    BillingPortalSessionBuilder::new(users_stripe_cust_id)
        .set_return_url(Some("https://someurl.com"))
        .build()
 ).await?;
```

### Additional context
Willing to work on this myself if it's something we'd be interested in adding :)

**Comment by augustoccesar** [comment]
Hello! This is being implemented on the [next branch](https://github.com/arlyon/async-stripe/tree/next) ([tracking PR](https://github.com/arlyon/async-stripe/pull/526))!

https://github.com/arlyon/async-stripe/blob/48d46533eb7557f492adc857c242a4c002bcdd33/generated/async-stripe-billing/src/billing_portal_session/types.rs#L45-L56

**Comment by antonio-hickey** [comment]
Ahh ok cool thanks, sorry I did a search on existing issues and didn't see anything related.

Will close this issue.

**Comment by aaronpeacock** [comment]
It would be extremely useful to have an example of how to do a  Billing Portal Session in the next branch.
There is no Billing Portal example yet in any branch.
This issue contains the only example I have seen so far, anywhere in the world,  and this is merely an example of code they DON'T want to write. At no point is there any example or guide to what must be done to instantiate a Billing Portal Session, nor are the docs any clearer.
https://docs.rs/async-stripe-billing/1.0.0-alpha.2/stripe_billing/struct.BillingPortalSession.html

For other people (like me) who arrived here looking for anything on the Billing Portal,  this fits the general "next" branch pattern of doing business, similar to other API endpoints...

```
  let billing_portal = stripe_billing::billing_portal_session::CreateBillingPortalSession::new(stripe_customer_id)
  .return_url( format!("https://website.com/user/{}", user_public_id) )
  .send(&client)
  .await
```


In my view, a Billing Portal example is essential for next, and next is now suddenly necessary to use, due to this crate not building anymore on the main branch!  (issue #703 )
