### ISSUE TITLE
Error on creating SubscriptionItemPriceDataRecurring

### ISSUE THREAD

**Issue by raulsi** [arlyon/async-stripe#66]
Struct PlanInterval exist multiple places which is causing issue when creating the subscription with a inline price plan:

```
let recurring: stripe::SubscriptionItemPriceDataRecurring = stripe::SubscriptionItemPriceDataRecurring {
      interval: stripe::PlanInterval::Month,
      interval_count: Some(100),
};
```

this Gives Error :

```
 interval: stripe::PlanInterval::Month,
    |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected enum 'stripe::resources::generated::billing::subscription::PlanInterval', found enum 'PlanInterval'    
```
    
I tried removing the extra struct in file subscriptions.rs and subscription_item.rs and import on top it's working this way.

Let me know if there is better way. (Will submit the PR with this changes)

**Comment by arlyon** [comment]
We cannot manually remove code from generated files as they will be overwritten next time the changes are reapplied from stripe. In any case, I think keeping these seperate is better as we can't guarantee that the 3 data structures will remain identical forever and may break in subtle (breaking) ways in the future.

The only solution is to make sure you use `subscription::PlanInterval` for subscriptions and the other ones in the other cases.

**Comment by raulsi** [comment]
@arlyon yes but the problem is another. can't import this module directly.

is there any way to fix this or we have to change the resource to public ?


![image](https://user-images.githubusercontent.com/7203127/123885136-becf4880-d987-11eb-8164-271ab580f5a5.png)

**Comment by arlyon** [comment]
Yes, sorry, my bad. I understand the problem now. The issue lies with rust and how it handles wildcard exports. The default behaviour is to ignore any clashing names which is why only the first is exported. The solution to this problem in nontrivial, and I wonder if these is a clippy lint that can warn about this in the future. I can imagine a whole host of bugs that could arise from this behavious (rather than opting for a compiler error). Let me have a look at this and get back to you.

Thanks for the report (and patience!).
